Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RoomRental.Attributes;
using RoomRental.Models;
using RoomRental.Services;
using RoomRental.ViewModels;
using RoomRental.ViewModels.FilterViewModels;
using RoomRental.ViewModels.SortStates;
using RoomRental.ViewModels.SortViewModels;

namespace RoomRental.Controllers
{
    [Authorize]
    public class RoomsController : Controller
    {
        private readonly RoomService _cache;
        private readonly BuildingService _buildingCache;
        private readonly RoomImageService _imageCache;
        private readonly int _pageSize = 10;
        private readonly IWebHostEnvironment _appEnvironment;

        public RoomsController(RoomService cache, BuildingService buildingCache, RoomImageService imageCache, IWebHostEnvironment appEnvironment, IConfiguration appConfig)
        {
            _cache = cache;
            _buildingCache = buildingCache;
            _imageCache = imageCache;
            _appEnvironment = appEnvironment;
            _pageSize = int.Parse(appConfig["Parameters:PageSize"]);
        }

        // GET: Rooms
        public async Task<IActionResult> Index(RoomFilterViewModel filterViewModel, int page = 1, RoomSortState sortOrder = RoomSortState.BuildingNameAsc)
        {
            var dict = Infrastructure.SessionExtensions.Get(HttpContext.Session, "Room");

            if (dict != null)
            {
                filterViewModel.BuildingNameFind = dict["BuildingNameFind"];

                Decimal areaFind;
                if (dict.ContainsKey("AreaFind") && Decimal.TryParse(dict["AreaFind"], out areaFind))
                    filterViewModel.AreaFind = areaFind;
                else
                    filterViewModel.AreaFind = null;
            }

            var rooms = await _cache.GetAll();

            //Фильтрация
            if (!String.IsNullOrEmpty(filterViewModel.BuildingNameFind))
                rooms = rooms.Where(e => e.Building.Name.Contains(filterViewModel.BuildingNameFind)).ToList();
            if (filterViewModel.AreaFind != null)
                rooms = rooms.Where(e => e.Area == filterViewModel.AreaFind).ToList();

            //Сортировка
            switch (sortOrder)
            {
                case RoomSortState.BuildingNameAsc:
                    rooms = rooms.OrderBy(e => e.Building.Name).ToList();
                    break;
                case RoomSortState.BuildingNameDesc:
                    rooms = rooms.OrderByDescending(e => e.Building.Name).ToList();
                    break;
                case RoomSortState.AreaAsc:
                    rooms = rooms.OrderBy(e => e.Area).ToList();
                    break;
                default:
                    rooms = rooms.OrderByDescending(e => e.Area).ToList();
                    break;
            }

            //Разбиение на страницы
            int count = rooms.Count;
            rooms = rooms.Skip((page - 1) * _pageSize).Take(_pageSize).ToList();

            //Формирование модели представления
            RoomsViewModel roomsViewModel = new RoomsViewModel()
            {
                Rooms = rooms,
                PageViewModel = new PageViewModel(page, count, _pageSize),
                FilterViewModel = filterViewModel,
                SortViewModel = new RoomSortViewModel(sortOrder)
            };

            return View(roomsViewModel);
        }

        // GET: Rooms/Filter
        [HttpGet]
        [SetSession("Room")]
        public async Task<IActionResult> Filter(RoomFilterViewModel filterViewModel, RoomSortState sortOrder = RoomSortState.BuildingNameAsc)
        {
            var routeValues = new RouteValueDictionary
            {
                { "filterViewModel", filterViewModel },
                { "sortOrder", sortOrder }
            };

            return RedirectToAction(nameof(Index), routeValues);
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _cache.GetAll() == null)
            {
                return NotFound();
            }

            var room = await _cache.Get(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public async Task<IActionResult> Create()
        {
            ViewData["BuildingId"] = new SelectList(await _buildingCache.GetAll(), "BuildingId", "Name");
            return View();
        }

        // POST: Rooms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomId,BuildingId,RoomNumber,Area,Description,Photos")] Room room)
        {
            if (ModelState.IsValid)
            {
                int? roomId = await _cache.Add(room);

                string[] paths = new string[room.Photos.Count()];
                Console.WriteLine(paths.Length);
                for (int i = 0; i < paths.Length; i++)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(room.Photos[i].FileName);

                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + Path.Combine("\\images\\Rooms\\", fileName), FileMode.Create))
                    {
                        await room.Photos[i].CopyToAsync(fileStream);
                    }

                    await _imageCache.Add(new RoomImage()
                    {
                        ImagePath = Path.Combine("\\images\\Rooms\\", fileName),
                        RoomId = (int)roomId
                    });
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildingId"] = new SelectList(await _buildingCache.GetAll(), "BuildingId", "Name", room.BuildingId);
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _cache.GetAll() == null)
            {
                return NotFound();
            }

            var room = await _cache.Get(id);
            if (room == null)
            {
                return NotFound();
            }

            ViewData["BuildingId"] = new SelectList(await _buildingCache.GetAll(), "BuildingId", "Name", room.BuildingId);
            return View(room);
        }

        // POST: Rooms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,BuildingId,RoomNumber,Area,Description")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _cache.Update(room);

                    /*await _imageCache.DeleteImageForRoom(room.RoomId);
                    string[] paths = new string[room.Photos.Count()];
                    for (int i = 0; i < paths.Length; i++)
                    {
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(room.Photos[i].FileName);

                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + Path.Combine("\\images\\Rooms\\", fileName), FileMode.Create))
                        {
                            await room.Photos[i].CopyToAsync(fileStream);
                        }

                        await _imageCache.Add(new RoomImage()
                        {
                            ImagePath = Path.Combine("\\images\\Rooms\\", fileName),
                            RoomId = (int)room.RoomId
                        });
                    }*/
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await RoomExistsAsync((int)room.RoomId)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildingId"] = new SelectList(await _buildingCache.GetAll(), "BuildingId", "Name", room.BuildingId);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _cache.GetAll() == null)
            {
                return NotFound();
            }

            var room = await _cache.Get(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        public async Task<IActionResult> DeleteImage(int imageId, int roomId)
        {
            await _imageCache.Delete(await _imageCache.GetImageAtId(imageId));

            return RedirectToAction(nameof(Edit), new RouteValueDictionary
            {
                { "id", roomId }
            });
        }

        public async Task<IActionResult> AddImage(List<IFormFile> images, int roomId)
        {
            string[] paths = new string[images.Count()];
            for (int i = 0; i < paths.Length; i++)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(images[i].FileName);

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + Path.Combine("\\images\\Rooms\\", fileName), FileMode.Create))
                {
                    await images[i].CopyToAsync(fileStream);
                }

                await _imageCache.Add(new RoomImage()
                {
                    ImagePath = Path.Combine("\\images\\Rooms\\", fileName),
                    RoomId = roomId
                });
            }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoomRental</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/RoomRental.styles.css" asp-append-version="true" /> *@

    <link rel="stylesheet" href=@($"https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.core.min.css")>
</head>
<body>
    <div class="wrapper">
        <header>
            <div>
                <div class="logo">
                    <a class="app-name" asp-area="" asp-controller="Home" asp-action="Index">RoomRental</a>
                </div>
                <nav>
                    <partial name="_NavigationPartial" />
                    <partial name="_LoginPartial" />
                </nav>
            </div>
        </header>

        <main role="main">
            @RenderBody()
        </main>

        <footer>
            <div class="footer_copyright">
                <div class="copyright_text">
                    <div>
                        &copy; 2023 - RoomRental - <span><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></span>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src=@($"https://cdn.jsdelivr.net/npm/@glidejs/glide")></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavigationPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@* @{
    var user = await UserManager.GetUserAsync(User);
    var lastName = user.Surname + " " + user.Name;
} *@
<div class="nav-tables">
    @if (!User.Identity.IsAuthenticated)
    {
        <a asp-area="" asp-controller="Buildings" asp-action="Index">Здания</a>
        <a asp-area="" asp-controller="Rooms" asp-action="Index">Помещения</a>
        <a asp-area="" asp-controller="Rentals" asp-action="Index">Аренда</a>
        <a asp-area="" asp-controller="Invoices" asp-action="Index">Счета</a>
    }
    else if (User.IsInRole("Admin"))
    {
        <a asp-area="" asp-controller="Organizations" asp-action="Index">Организации</a>
        <a asp-area="" asp-controller="Buildings" asp-action="Index">Здания</a>
        <a asp-area="" asp-controller="Rooms" asp-action="Index">Помещения</a>
        <a asp-area="" asp-controller="Rentals" asp-action="Index">Аренда</a>
        <a asp-area="" asp-controller="Invoices" asp-action="Index">Счета</a>
    }
    else if (User.IsInRole("User"))
    {
        <div class="dropdown">
            <a asp-area="" asp-controller="Organizations" class="dropbtn" asp-action="Details" asp-route-id=@UserManager.GetUserAsync(User).Result?.OrganizationId>Организация</a>
        </div>
        <div class="dropdown">
            <a asp-area="" asp-controller="Buildings" asp-action="Index" class="dropbtn">Здания</a>
        </div>
        <div class="dropdown">
            <a asp-area="" asp-controller="Rooms" asp-action="Index" class="dropbtn">Помещения</a>
        </div>
        <div class="dropdown">
            <a asp-area="" asp-controller="Rentals" asp-action="Index" class="dropbtn">Аренда</a>
            <div class="dropdown-content">
                <a asp-area="" asp-controller="Rentals" asp-action="OurRentals">Аренда</a>
            </div>
        </div>
        <div class="dropdown">
            <a asp-area="" asp-controller="Invoices" asp-action="Index" class="dropbtn">Счета</a>
            <div class="dropdown-content">
                <a asp-area="" asp-controller="Invoices" asp-action="OurInvoices">Счета</a>
            </div>
        </div>
    }
</div>