Models/Invoice.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using RoomRental.Attributes;
using System.ComponentModel.DataAnnotations.Schema;

namespace RoomRental.Models;

public partial class Invoice
{
    [Display(Name = "Идентификатор")]
    public int InvoiceId { get; set; }

    [Required(ErrorMessage = "Не указана организация-арендатор")]
    [Display(Name = "Организация-арендатор")]
    public int RentalOrganizationId { get; set; }

    [Required(ErrorMessage = "Не указано помещение")]
    [Display(Name = "Помещение")]
    public int RoomId { get; set; }

    [Required(ErrorMessage = "Не указана сумма оплаты")]
    [Display(Name = "Сумма оплаты")]
    [Range(0, double.MaxValue, ErrorMessage = "Значение не может быть меньше нуля")]
    public decimal? Amount { get; set; }

    [Required(ErrorMessage = "Не указана дата заключения договора")]
    [Display(Name = "Дата заключения договора")]
    [DataType(DataType.Date)]
    public DateTime ConclusionDate { get; set; }

    [Required(ErrorMessage = "Не указана дата оплаты")]
    [Display(Name = "Дата оплаты")]
    [DataType(DataType.Date)]
    [CheckDate("ConclusionDate")]
    public DateTime PaymentDate { get; set; }

    [Required(ErrorMessage = "Не указан оформляющий")]
    [Display(Name = "Оформляющий")]
    public string ResponsiblePersonId { get; set; }

    [Display(Name = "Организация-арендатор")]
    [ValidateNever]
    public virtual Organization RentalOrganization { get; set; }

    [Display(Name = "Оформляющий")]
    [ValidateNever]
    public virtual User? ResponsiblePerson { get; set; } = null!;

    [ValidateNever]
    public virtual Room Room { get; set; } = null!;
}

// Ключ для аренд-счетов --- Помещение + организация + дата заключения договора

ViewModels/InvoicesViewModel.cs
using RoomRental.Models;
using RoomRental.ViewModels.FilterViewModels;
using RoomRental.ViewModels.SortViewModels;

namespace RoomRental.ViewModels
{
    public class InvoicesViewModel
    {
        public IEnumerable<Invoice?> Invoices { get; set; }
        public PageViewModel? PageViewModel { get; set; }
        public InvoiceFilterViewModel FilterViewModel { get; set; }
        public InvoiceSortViewModel SortViewModel { get; set; }
    }
}

Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RoomRental.Attributes;
using RoomRental.Models;
using RoomRental.Services;
using RoomRental.ViewModels;
using RoomRental.ViewModels.FilterViewModels;
using RoomRental.ViewModels.SortStates;
using RoomRental.ViewModels.SortViewModels;

namespace RoomRental.Controllers
{
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly InvoiceService _cache;
        private readonly OrganizationService _organizationCache;
        private readonly RoomService _roomCache;
        private readonly RentalService _rentalCache;
        private readonly int _pageSize = 10;

        private readonly UserManager<User> _userManager;
        private readonly HttpContext _httpContext;

        public InvoicesController(InvoiceService cache, RoomService roomCache, OrganizationService organizationCache, RentalService rentalService,
            IConfiguration appConfig, UserManager<User> userManager, HttpContextAccessor httpContext)
        {
            _cache = cache;
            _organizationCache = organizationCache;
            _roomCache = roomCache;
            _rentalCache = rentalService;
            _pageSize = int.Parse(appConfig["Parameters:PageSize"]);
            _userManager = userManager;
            _httpContext = httpContext.HttpContext;
        }

        // GET: Invoices
        public async Task<IActionResult> Index(InvoiceFilterViewModel filterViewModel, int page = 1, InvoiceSortState sortOrder = InvoiceSortState.OrganizationNameAsc)
        {
            var dict = Infrastructure.SessionExtensions.Get(HttpContext.Session, "Invoice");

            /*if (dict != null)
            {
                filterViewModel.ResponsiblePersonFind = dict["ResponsiblePersonFind"];
                filterViewModel.OrganizationNameFind = dict["OrganizationNameFind"];

                DateTime date;
                if (dict.ContainsKey("PaymentDateFind") && DateTime.TryParse(dict["PaymentDateFind"], out date))
                    filterViewModel.PaymentDateFind = date;
                else
                    filterViewModel.PaymentDateFind = null;

                if (dict.ContainsKey("ConclusionDateFind") && DateTime.TryParse(dict["ConclusionDateFind"], out date))
                    filterViewModel.ConclusionDateFind = date;
                else
                    filterViewModel.ConclusionDateFind = null;

                if (dict.ContainsKey("PermissionDateFind") && DateTime.TryParse(dict["PermissionDateFind"], out date))
                    filterViewModel.PermissionDateFind = date;
                else
                    filterViewModel.PermissionDateFind = null;

                Decimal amountFind;
                if (dict.ContainsKey("AmountFind") && Decimal.TryParse(dict["AmountFind"], out amountFind))
                    filterViewModel.AmountFind = amountFind;
                else
                    filterViewModel.AmountFind = null;
            }*/

            List<Invoice> invoices = null;
            if (_httpContext.User.IsInRole("Admin"))
                invoices = await _cache.GetAll();
            else
                invoices = (await _cache.GetAll()).Where(e => e.RentalOrganizationId != _userManager.GetUserAsync(_httpContext.User).Result.OrganizationId).ToList();

            invoices = await SortSearch(invoices, dict, filterViewModel, sortOrder);

            /*//Фильтрация
            if (!String.IsNullOrEmpty(filterViewModel.OrganizationNameFind))
                invoices = invoices.Where(e => e.RentalOrganization.Name.Contains(filterViewModel.OrganizationNameFind)).ToList();
            if (!String.IsNullOrEmpty(filterViewModel.ResponsiblePersonFind))
                invoices = invoices.Where(e => e.ResponsiblePerson.SNL.Contains(filterViewModel.ResponsiblePersonFind)).ToList();
            if (filterViewModel.AmountFind != null)
                invoices = invoices.Where(e => e.Amount == filterViewModel.AmountFind).ToList();
            if (filterViewModel.ConclusionDateFind != null)
                invoices = invoices.Where(e => e.ConclusionDate == filterViewModel.ConclusionDateFind).ToList();
            if (filterViewModel.PaymentDateFind != null)
                invoices = invoices.Where(e => e.PaymentDate == filterViewModel.PaymentDateFind).ToList();


            /////////////////////////////////////////////////////////////////////////////////////////////////////////
            /// Фильтрация должников
            if (filterViewModel.PermissionDateFind != null)
                invoices = invoices.Where(e => e.PaymentDate > filterViewModel.PermissionDateFind && e.ConclusionDate <= filterViewModel.PermissionDateFind
                || (e.PaymentDate <= filterViewModel.PermissionDateFind
                        && (_rentalCache.GetAll().Result).Single(r => r.CheckInDate == e.ConclusionDate && r.RentalOrganizationId == e.RentalOrganizationId && r.Room.RoomId == e.RoomId).Amount > e.Amount))
                    .ToList();
            /////////////////////////////////////////////////////////////////////////////////////////////////////////


            //Сортировка
            switch (sortOrder)
            {
                case InvoiceSortState.OrganizationNameAsc:
                    invoices = invoices.OrderBy(e => e.RentalOrganization.Name).ToList();
                    break;
                case InvoiceSortState.OrganizationNameDesc:
                    invoices = invoices.OrderByDescending(e => e.RentalOrganization.Name).ToList();
                    break;
                case InvoiceSortState.PaymentDateAsc:
                    invoices = invoices.OrderBy(e => e.PaymentDate).ToList();
                    break;
                case InvoiceSortState.PaymentDateDesc:
                    invoices = invoices.OrderByDescending(e => e.PaymentDate).ToList();
                    break;
                case InvoiceSortState.ConclusionDateAsc:
                    invoices = invoices.OrderBy(e => e.ConclusionDate).ToList();
                    break;
                case InvoiceSortState.ConclusionDateDesc:
                    invoices = invoices.OrderByDescending(e => e.ConclusionDate).ToList();
                    break;
                case InvoiceSortState.AmountAsc:
                    invoices = invoices.OrderBy(e => e.Amount).ToList();
                    break;
                case InvoiceSortState.AmountDesc:
                    invoices = invoices.OrderByDescending(e => e.Amount).ToList();
                    break;
                case InvoiceSortState.ResponsiblePersonAsc:
                    invoices = invoices.OrderBy(e => e.ResponsiblePersonId).ToList();
                    break;
                default:
                    invoices = invoices.OrderByDescending(e => e.ResponsiblePersonId).ToList();
                    break;
            }*/

            //Разбиение на страницы
            int count = invoices.Count;
            invoices = invoices.Skip((page - 1) * _pageSize).Take(_pageSize).ToList();

            //Формирование модели представления
            InvoicesViewModel invoicesViewModel = new InvoicesViewModel()
            {
                Invoices = invoices,
                PageViewModel = new PageViewModel(page, count, _pageSize),
                FilterViewModel = filterViewModel,
                SortViewModel = new InvoiceSortViewModel(sortOrder)
            };

            return View(invoicesViewModel);
        }

        // GET: Invoices/Filter
        [HttpGet]
        [SetSession("Invoice")]
        public async Task<IActionResult> Filter(InvoiceFilterViewModel filterViewModel, InvoiceSortState sortOrder = InvoiceSortState.OrganizationNameAsc)
        {
            var routeValues = new RouteValueDictionary
            {
                { "filterViewModel", filterViewModel },
                { "sortOrder", sortOrder }
            };

            return RedirectToAction(nameof(Index), routeValues);
        }

        public async Task<IActionResult> OurInvoices(InvoiceFilterViewModel filterViewModel, int page = 1, InvoiceSortState sortOrder = InvoiceSortState.OrganizationNameAsc)
        {
            var dict = Infrastructure.SessionExtensions.Get(HttpContext.Session, "OurInvoice");

            /*if (dict != null)
            {
                filterViewModel.ResponsiblePersonFind = dict["ResponsiblePersonFind"];
                filterViewModel.OrganizationNameFind = dict["OrganizationNameFind"];

                DateTime date;
                if (dict.ContainsKey("PaymentDateFind") && DateTime.TryParse(dict["PaymentDateFind"], out date))
                    filterViewModel.PaymentDateFind = date;
                else
                    filterViewModel.PaymentDateFind = null;

                if (dict.ContainsKey("ConclusionDateFind") && DateTime.TryParse(dict["ConclusionDateFind"], out date))
                    filterViewModel.ConclusionDateFind = date;
                else
                    filterViewModel.ConclusionDateFind = null;

                if (dict.ContainsKey("PermissionDateFind") && DateTime.TryParse(dict["PermissionDateFind"], out date))
                    filterViewModel.PermissionDateFind = date;
                else
                    filterViewModel.PermissionDateFind = null;

                Decimal amountFind;
                if (dict.ContainsKey("AmountFind") && Decimal.TryParse(dict["AmountFind"], out amountFind))
                    filterViewModel.AmountFind = amountFind;
                else
                    filterViewModel.AmountFind = null;
            }*/

            var invoices = (await _cache.GetAll()).Where(e => e.RentalOrganizationId == _userManager.GetUserAsync(_httpContext.User).Result.OrganizationId).ToList();

Views/Invoices/Create.cshtml
@model RoomRental.Models.Invoice

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <h1>Оплата аренды</h1>

    <div class="create-form-container">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-div">
                <label asp-for="RentalOrganizationId" class="control-label"></label>
                <select class="filter-input" asp-for="RentalOrganizationId" class="form-control" asp-items="ViewBag.RentalOrganizationId"></select>
            </div>
            <div class="form-div">
                <label asp-for="RoomId" class="control-label"></label>
                <select class="filter-input" asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
            </div>
            <div class="form-div">
                <label asp-for="Amount" class="control-label"></label>
                <input class="filter-input" asp-for="Amount" placeholder="Сумма оплаты" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="ConclusionDate" class="control-label"></label>
                <input class="filter-input" asp-for="ConclusionDate" class="form-control" />
                <span asp-validation-for="ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input class="filter-input" asp-for="PaymentDate" class="form-control" placeholder="Дата оплаты" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="ResponsiblePersonId" class="control-label"></label>
                <select class="filter-input" asp-for="ResponsiblePersonId" asp-items="ViewBag.ResponsiblePerson"></select>
            </div>
            <div class="buttons">
                <a class="btn-primary submitButton-index" asp-action="Index">Возврат к списку</a>
                <input class="submitButton-index" type="submit" value="Создать" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Invoices/Delete.cshtml
@model RoomRental.Models.Invoice
@inject RoomRental.Services.RoomService rooms

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <h1>Удаление оплаты</h1>

    <h3>Вы действительно хотите удалить эту запись?</h3>
    <div class="det-container">
        <div>
            <label>@Html.DisplayNameFor(model => model.Amount):</label>
            @Html.DisplayFor(model => model.Amount)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.ConclusionDate):</label>
            @Html.DisplayFor(model => model.ConclusionDate)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.PaymentDate):</label>
            @Html.DisplayFor(model => model.PaymentDate)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.RentalOrganization):</label>
            @Html.DisplayFor(model => model.RentalOrganization.Name)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.ResponsiblePerson):</label>
            @Model.ResponsiblePerson.SNL
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.Room):</label>
            @((await rooms.TryGet(Model.RoomId)).Building.Name), № @((await rooms.TryGet(Model.RoomId)).RoomNumber)
        </div>
    </div>
    <div class="det-container">
        <form asp-action="Delete">
            <input type="hidden" asp-for="InvoiceId" />
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-primary">Возврат к списку</a>
        </form>
    </div>
</div>

Views/Invoices/Details.cshtml
@model RoomRental.Models.Invoice
@inject UserManager<User> userManager
@inject RoomRental.Services.RoomService rooms

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1>Счет оплаты</h1>
    <div class="det-container">
        <div>
            <label>@Html.DisplayNameFor(model => model.Amount):</label>
            @Html.DisplayFor(model => model.Amount)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.ConclusionDate):</label>
            @Html.DisplayFor(model => model.ConclusionDate)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.PaymentDate):</label>
            @Html.DisplayFor(model => model.PaymentDate)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.RentalOrganization):</label>
            @Html.DisplayFor(model => model.RentalOrganization.Name)
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.ResponsiblePerson):</label>
            @Model.ResponsiblePerson.SNL
        </div>
        <div>
            <label>@Html.DisplayNameFor(model => model.Room):</label>
            @((await rooms.TryGet(Model.RoomId)).Building.Name), № @((await rooms.TryGet(Model.RoomId)).RoomNumber)
        </div>
    </div>
    <div class="det-container">
        @if(User.IsInRole("Admin") || (await userManager.GetUserAsync(User)).OrganizationId != Model.RentalOrganizationId)
        {
            <a class="btn-primary btn" asp-action="Edit" asp-route-id="@Model?.InvoiceId">Изменить</a>
            <span>|</span>
            <a class="btn-primary btn" asp-action="Index">Возврат к списку</a>
        }
        else
        {
            <a class="btn-primary btn" asp-action="OurInvoices">Возврат к списку</a>
        }
    </div>
</div>

Views/Invoices/Edit.cshtml
@model RoomRental.Models.Invoice

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h1>Редактирование оплаты</h1>
    <div class="create-form-container">
        <form asp-action="Edit">
            <input type="hidden" asp-for="InvoiceId" />
            <div class="form-div">
                <label asp-for="RentalOrganizationId" class="control-label"></label>
                <select class="filter-input" asp-for="RentalOrganizationId" class="form-control" asp-items="ViewBag.RentalOrganizationId"></select>
            </div>
            <div class="form-div">
                <label asp-for="RoomId" class="control-label"></label>
                <select class="filter-input" asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
            </div>
            <div class="form-div">
                <label asp-for="Amount" class="control-label"></label>
                <input class="filter-input" asp-for="Amount" placeholder="Сумма оплаты" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="ConclusionDate" class="control-label"></label>
                <input class="filter-input" asp-for="ConclusionDate" class="form-control" />
                <span asp-validation-for="ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input class="filter-input" asp-for="PaymentDate" class="form-control" placeholder="Дата оплаты" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-div">
                <label asp-for="ResponsiblePersonId" class="control-label"></label>
                <select class="filter-input" asp-for="ResponsiblePersonId" asp-items="ViewBag.ResponsiblePerson"></select>
            </div>
            <div class="buttons">
                <a class="submitButton-index btn-primary" asp-action="Index">Возврат к списку</a>
                <input class="submitButton-index" type="submit" value="Изменить" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Invoices/OurInvoices.cshtml
@model RoomRental.ViewModels.InvoicesViewModel
@inject RoomRental.Services.RoomService rooms
@{
    ViewData["Title"] = "OurInvoices";

    decimal? amountFind = Model.FilterViewModel.AmountFind;
    string personFind = Model.FilterViewModel.ResponsiblePersonFind;
    DateTime? paymentDateFind = Model.FilterViewModel.PaymentDateFind;
    DateTime? conclusionDateFind = Model.FilterViewModel.ConclusionDateFind;
    DateTime? permissionDateFind = Model.FilterViewModel.PermissionDateFind;
}

<div class="index-container">
    <div class="form-container">
        <div class="tabs">
            <h3>Фильтрация</h3>
            <div><a asp-action="Create">Создать</a></div>
        </div>
        <div class="form-container_two">
            <form method="get" asp-action="OurFilter">
                <div class="form-div">
                    <label class="white-label">Сумма</label>
                    <input class="filter-input" type="text" step="any" name="AmountFind" value="@(amountFind)" oninput="this.value = this.value.replace(/[^0-9,]/g, '')" placeholder="Сумма" />
                </div>
                <div class="form-div">
                    <label class="white-label">Ответственное лицо</label>
                    <input class="filter-input" name="ResponsiblePersonFind" value="@personFind" placeholder="Ответственное лицо" />
                </div>
                <div class="form-div">
                    <label class="white-label">Дата оформления</label>
                    <input class="filter-input" type="date" name="ConclusionDateFind" value="@conclusionDateFind?.ToString("yyyy-MM-dd")" placeholder="Дата оформления" />
                </div>
                <div class="form-div">
                    <label class="white-label">Дата платежа</label>
                    <input class="filter-input" type="date" name="PaymentDateFind" value="@paymentDateFind?.ToString("yyyy-MM-dd")" placeholder="Дата платежа" />
                </div>
                <div class="form-div">
                    <label class="white-label">Дата  для поиска должников</label>
                    <input class="filter-input" type="date" name="PermissionDateFind" value="@permissionDateFind?.ToString("yyyy-MM-dd")" placeholder="Дата для поиска задолников" />
                </div>
                <input class="filter-input" type="hidden" name="sortOrder" value="@Model.SortViewModel.Current" />
                <input class="submitButton-index" type="submit" value="Поиск" />
            </form>
        </div>
    </div>

    <div class="table-container">
        <h1>Счета-фактуры</h1>
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th class="element">
                            @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().RoomId)
                        </th>
                        <th class="element">
                            <a asp-action="OurInvoices"
                               asp-route-sortOrder="@(Model.SortViewModel.OrganizationNameSort)"
                               asp-route-amountFind="@amountFind"
                               asp-route-personFind="@personFind"
                               asp-route-paymentDateFind="@conclusionDateFind"
                               asp-route-paymentDateFind="@permissionDateFind"
                               asp-route-paymentDateFind="@paymentDateFind">
                                @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().RentalOrganization)
                            </a>
                        </th>
                        <th class="element">
                            <a asp-action="OurInvoices"
                               asp-route-sortOrder="@(Model.SortViewModel.AmountSort)"
                               asp-route-amountFind="@amountFind"
                               asp-route-personFind="@personFind"
                               asp-route-paymentDateFind="@conclusionDateFind"
                               asp-route-paymentDateFind="@permissionDateFind"
                               asp-route-paymentDateFind="@paymentDateFind">
                                @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().Amount)
                            </a>
                        </th>
                        <th class="element">
                            <a asp-action="OurInvoices"
                               asp-route-sortOrder="@(Model.SortViewModel.ConclusionDateSort)"
                               asp-route-amountFind="@amountFind"
                               asp-route-personFind="@personFind"
                               asp-route-paymentDateFind="@conclusionDateFind"
                               asp-route-paymentDateFind="@permissionDateFind"
                               asp-route-paymentDateFind="@paymentDateFind">
                                @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().ConclusionDate)
                            </a>
                        </th>
                        <th class="element">
                            <a asp-action="OurInvoices"
                               asp-route-sortOrder="@(Model.SortViewModel.PaymentDateSort)"
                               asp-route-amountFind="@amountFind"
                               asp-route-personFind="@personFind"
                               asp-route-paymentDateFind="@conclusionDateFind"
                               asp-route-paymentDateFind="@permissionDateFind"
                               asp-route-paymentDateFind="@paymentDateFind">
                                @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().PaymentDate)
                            </a>
                        </th>
                        <th class="element">
                            <a asp-action="OurInvoices"
                               asp-route-sortOrder="@(Model.SortViewModel.ResponsiblePersonSort)"
                               asp-route-amountFind="@amountFind"
                               asp-route-personFind="@personFind"
                               asp-route-paymentDateFind="@conclusionDateFind"
                               asp-route-paymentDateFind="@permissionDateFind"
                               asp-route-paymentDateFind="@paymentDateFind">
                                @Html.DisplayNameFor(model => model.Invoices.SingleOrDefault().ResponsiblePerson)
                            </a>
                        </th>
                        @* <th class="element"></th> *@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Invoices)
                    {
                        <tr class="row" onclick="location.href='@Url.Action("Details", "Invoices", new { id = item.InvoiceId })'">
                            <td class="element">
                                @((await rooms.TryGet(item.RoomId)).Building.Name),<br />  № @((await rooms.TryGet(item.RoomId)).RoomNumber)
                            </td>
                            <td class="element">
                                <a asp-controller="Organizations" asp-action="Details" asp-route-id="@item.RentalOrganizationId">@Html.DisplayFor(modelItem => item.RentalOrganization.Name) </a>
                            </td>
                            <td class="element">
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td class="element">
                                @Html.DisplayFor(modelItem => item.ConclusionDate)
                            </td>
                            <td class="element">
                                @Html.DisplayFor(modelItem => item.PaymentDate)
                            </td>
                            <td class="element">
                                @item.ResponsiblePerson.SNL
                            </td>
                            @* <td class="element">
                                <a class="btn-primary btn" asp-action="Edit" asp-route-id="@item.InvoiceId">Изменить</a> |
                                <a class="btn-danger btn" asp-action="Delete" asp-route-id="@item.InvoiceId">Удалить</a>
                            </td> *@
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <page-link page-model="Model.PageViewModel" page-action="OurInvoices"
                   page-url-sortOrder="@(Model.SortViewModel.Current)"
                   page-url-amountFind="@amountFind"
                   page-url-personFind="@personFind"
                   page-url-paymentDateFind="@conclusionDateFind"
                   page-url-paymentDateFind="@permissionDateFind"
                   page-url-paymentDateFind="@paymentDateFind"></page-link>
    </div>
</div>